### PR TITLE
Fix small typos

### PR DESCRIPTION
**Pull request by bwignall**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Any chance we could get this merged?

**Comment by tomjaguarpaw** [comment]
@TikhonJelvis Given the two reviewer system you have just informed me about, would you mind reviewing this one?

**Comment by TikhonJelvis** [comment]
Oh, I'm sorry for any confusion—the Haskell Platform and its website are currently managed as a separate project, similar to the cabal website... etc, so it has its own merging policies. It might make sense to consolidate the website components at some point, but we haven't done that.

**Comment by tomjaguarpaw** [comment]
I see. Merging the policies would be a good first step!  The biggest impediment to making these kind of contributions is actually knowing how to navigate around the development process.

**Comment by ketzacoatl** [comment]
Let's get this reviewed and merged before there's a conflict that requires another iteration updates

@TikhonJelvis, sorry for the ping, but maybe you know who to ping to unblock this? (Who do we talk to to get this moving?)

**Comment by TikhonJelvis** [comment]
@gbaz

**Comment by gbaz** [comment]
II'll try to get to this in the next few days, sorry it slipped through the cracks.

**Review by gbaz — APPROVED** [review]

**Comment by gbaz** [comment]
note these were not changes to the website, but to installers and since we're not building new installers anytime soon, there's nothing to deploy here. Nonetheless, merging.

**Pull request merged**
