### PR TITLE
Tweak to GhcInstallAction; distinguish a phonyTargetDir

### PR DESCRIPTION
**Pull request by randen**
These are two commits that have been needed for the Windows installer builds.  For the Windows HP build, the installation looks different on the user's machine from the other HP build environments. Due to this, these changes are specific to the Windows HP but are in code common to all environments.  I am unable to test these changes on those other build environments, so these changes should be applied with that caveat.  I have tried to make these edits innocuous to the other environments, but from HP build/installation problems in the past, I observe that those other environments have their own delicateness that might be affected.  The one involving GhcInstallAction is very unlikely to have any imact, but I am more concerned with the phonyTargetDir change's effects.

### CODE REVIEW

**Comment by gbaz** [comment]
Thanks randy. Do you mind explaining the motivation a bit more when you get a chance. I think the latter change especially might be a good thing elsewhere, if anything...

**Comment by randen** [comment]
@gbaz (I am able to get back to this now, sorry.)  There are more details in each of the two commits in this PR.  Do those provide sufficient info for you?  (I probably got the git process wrong by putting details in each commit rather than in the PR?)

**Comment by gbaz** [comment]
Ah -- my mistake as well for not seeing them there... I think I changed a related thing for mac already!

For posterity here's the details:

Allow a GhcInstallAction to skip directory enumeration

The Windows build is different from the other builds in a few
ways, one of which is very important for this commit:

* Windows installs HP and GHC in a single directory, so
  creating dependencies too early on the contents of the
  target GHC directory contents will cause Shake to complain
  that the directory contents have changed since making a
  dependency on them (which they have, since later, the
  HP-built packages need to come into that set of
  directories).  So, after building the ghcVirtualTarget, we
  do not want the directory contents accounted for as
  dependencies just yet (it is done later for the entire
  target directory).

In the osGhcTargetInstall function in the Windows builds, the
directory is not completed at the point this action is used,
so we cannot have the Shake system enumerating this directory
for dependencies too soon.  So we must make its
osGhcTargetInstall no longer returns a directory, which
prevents the vTarget code in Dirs.hs from making dependencies
of the directory contents too soon.

This change is part of a larger change but it is separated
here as this isolates any effects on the common code.  The
Windows-specific changes will be in a separate commit for
bookkeeping reasons.  The GhcInstallAction type is only used
internally to GhcDist and for the Windows case where it is
the only build (currently) to use the GhcInstallCustom
variant of the GhcInstall type.

* hptool/src/OS/Win.hs
  * With this change to GhcInstallAction, the
    osGhcTargetInstall function can now elide the
    (incomplete) FilePath.
* hptool/src/Types.hs
  * Allow the FilePath returned by a GhcInstallAction, to be
    optional.
* hptool/src/OS/Win/WinRules.hs
  * Track GhcInstallAction change
* hptool/src/GhcDist.hs
  * Allow the handling of ghcVirtualTarget to accomodate the
    case of not providing a FilePath, which will prevent the
    vdir code from creating dependencies on the contents.


Un-overload the "targetDir" target

If a FilePath matches a so-called "phony" target, Shake will
count this as satisfying the phony target and skip its steps.
Currently, the target called targetDir is overloaded, being
used in a "~>" rule (for defining a "phony" target) but it is
also used for contructing file paths, and it appears as a
dependency in some rules (e.g., "need [targetDir]"). When it
is a dependency, it actually should be upon a phony target,
not the actual directory.  Due to how dependencies are
constructed for the Windows HP build, this problem has
plagued it.

This change needs to be tested for the other build environments.

* hptool/src/Main.hs
* hptool/src/OS/Internal.hs
* hptool/src/OS/Mac.hs
* hptool/src/OS/Posix.hs
* hptool/src/OS/Win.hs
* hptool/src/OS/Win/WinNsis.hs
  * change the dependency upon targetDir to phonyTargetDir
* hptool/src/Paths.hs
  * define and export phonyTargetDir
* hptool/src/Target.hs
  * Change rule from targetDir to phonyTargetDir

**Comment by gbaz** [comment]
I'll merge and pull later today -- lgtm.

**Pull request merged**
